### ISSUE TITLE
What does the extra scetool flags do?

### ISSUE THREAD

**Issue by Spork-Schivago** [sguerrini97/psl1ghtv2_ports#1]
This isn't an issue, I just don't know how else to contact you.   What do the extra scetool flags do in the ppu_rules?  I know you said they're needed, but why?   You can contact me via nacho2874@yahoo.com if you want.  I'll check back here to see if you answer though.  Thanks.

**Comment by sguerrini97** [comment]
I think the important parameter is
"--self-ctrl-flags=4000000000000000000000000000000000000000000000000000000000000000", but I found easier to share the whole file.

It allow the executable to use syscalls that require root flags (http://www.ps3devwiki.com/ps3/LV2_Functions_and_Syscalls#LV2_Syscalls), otherwise most of the syscalls used in these ports return 80010003 ("The feature is not yet implemented"). Hope you got the answer.

**Comment by Spork-Schivago** [comment]
Wow, thank you!   I've been trying to figure out how to do that for a while now!   I try to maintain a more up-to-date version of the PS3 toolchain, located here:  http://github.com/Spork-Schivago/toolchain   I haven't worked on it in a while and it might currently be broke again.  Once I get some free time, i want to try updating the programs again.  Perhaps I should include your ppu_rules.   I know I tried modifying psl1ght and implement a symlink function.   I tried various things.  I even tried calling the syscall directly.  It always locks the PS3.   Perhaps this will help.  Thank you.
